version: '3.4'

volumes:
  l2_data:

services:
  l2:
    image: public.ecr.aws/i6b2w2n6/nitro-node:apechain-2.0.0
    ports:
      - "8545:8545"
      - "8546:8546"
    volumes:
      - "${PWD}/nodeConfig.json:/config/nodeConfig.json"
      - l2_data:/home/user/.arbitrum
    entrypoint:
      - "/usr/local/bin/nitro"
      - --conf.file=/config/nodeConfig.json
      - --execution.forwarding-target=https://apechain.calderachain.xyz/http
      - --node.feed.input.url=wss://apechain.calderachain.xyz/feed
      - --parent-chain.connection.url=https://arb1.arbitrum.io/rpc
      - --node.data-availability.rest-aggregator.urls="https://apechain.calderachain.xyz/rest-aggregator"
